# Generated by Django 4.1.3 on 2022-11-21 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_note', '0003_topic_topic_big'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='topic_big',
        ),
    ]
