# Generated by Django 4.1.3 on 2022-11-23 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_note', '0006_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='title',
            field=models.TextField(default='non_nullable', max_length=50),
            preserve_default=False,
        ),
    ]
