# Generated by Django 4.1.3 on 2022-11-23 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_note', '0007_entry_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='text',
        ),
        migrations.AlterField(
            model_name='topic',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
