# Generated by Django 4.1.3 on 2022-11-23 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_note', '0008_remove_entry_text_alter_topic_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='text',
            field=models.TextField(default='why', max_length=10000),
        ),
    ]
