# Generated by Django 4.1.3 on 2022-11-23 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_note', '0009_entry_text'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Entry',
            new_name='Post',
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name_plural': 'posts'},
        ),
    ]
